spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://product-service
          predicates:
            - Path=/products/**
          filters:
            - StripPrefix=1
        - id: order-service
          uri: http://order-service
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=1
        - id: shipment-service
          uri: http://shipment-service
          predicates:
            - Path:/shipments/**
          filters:
            - StripPrefix=1
        - id: user-service
          uri: http://user-service
          predicates:
            - Path:/users/**
          filters:
            - StripPrefix=1
        - id: payment-service
          uri: http://payment-service
          predicates:
            - Path:/payments/**
          filters:
            - StripPrefix=1
        - id: inventory-service
          uri: http://inventory-service
          predicates:
            - Path:/inventories/**
          filters:
            - StripPrefix=1